### ISSUE TITLE
Build fails when installing from PyPI due to missing files

### ISSUE THREAD

**Issue by rayrapetyan** [ethereum/eth-hash#24]
Similar to https://github.com/ethereum/eth-rlp/issues/6.

## What was wrong?
Building fails when trying to deploy package from PyPI archive. Normally users never perform installation like described below, but it's being done automatically when manually installing any other depending packages (e.g. py-evm).

### Code that produced the error
```sh
wget https://files.pythonhosted.org/packages/c7/f7/b7a29f683aa180fe70c070cc07a6750647e92d8ecca57c8cfa3f4f2318f2/eth-hash-0.2.0.tar.gz -O /tmp/eth-hash-0.2.0.tar.gz
cd /tmp
tar -xvf eth-hash-0.2.0.tar.gz
cd eth-hash-0.2.0
pip install .
```

### Full error output 

```sh
Processing /tmp/eth-hash-0.2.0
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__pycache__.__init__.cpython-36: module references __file__
    
    Installed /tmp/pip-req-build-d46ckv30/.eggs/pypandoc-1.4-py3.6.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-d46ckv30/setup.py", line 72, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/ara/venv_python/python3/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/ara/venv_python/python3/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/ara/venv_python/python3/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-req-build-d46ckv30/.eggs/setuptools_markdown-0.2-py3.6.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-req-build-d46ckv30/.eggs/pypandoc-1.4-py3.6.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-d46ckv30/
```

### Environment
```sh
python -m eth_utils
Python version:
3.6.5 (default, Aug 16 2018, 01:14:45) 
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]

Operating System: FreeBSD-11.2-RELEASE-p2-amd64-64bit-ELF

pip freeze result:
asn1crypto==0.24.0
cffi==1.11.5
cryptography==2.3.1
cytoolz==0.9.0.1
eth-bloom==1.0.0
eth-hash==0.1.4
eth-keys==0.2.0b3
eth-typing==1.1.0
eth-utils==1.2.0
hexbytes==0.1.0
idna==2.7
lru-dict==1.1.6
ptyprocess==0.6.0
py-ecc==1.4.3
pycparser==2.18
pypandoc==1.4
setuptools-markdown==0.2
six==1.11.0
toolz==0.9.0
``` 

## How can it be fixed?

Add missed files (especially README.md) into PyPI package.

**Comment by carver** [comment]
To repeat Piper's message from the same issue on eth-rlp:

> To fix the we need to add a MANIFEST.in file like this: https://github.com/ethereum/py-evm/blob/master/MANIFEST.in

**Comment by willianpaixao** [comment]
Hey @carver, this issue was fixed and can now be closed.
