### ISSUE TITLE
Allow importing of eth_hash.auto.keccak without the backend check

### ISSUE THREAD

**Issue by carver** [ethereum/eth-hash#8]
### Code that produced the error

```sh
pip install --user requests eth_utils tqdm
python tests/integration/install_parity.py $PARITY_VERSION
```

### Full error output 

```sh
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 7.0MB/s 
Collecting eth_utils
  Downloading eth_utils-1.0.1-py3-none-any.whl
Collecting tqdm
  Downloading tqdm-4.19.6-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 9.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.4MB/s 
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 7.4MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 9.0MB/s 
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 9.0MB/s 
Collecting cytoolz<1.0.0,>=0.8.2 (from eth_utils)
  Downloading cytoolz-0.9.0.tar.gz (443kB)
    100% |████████████████████████████████| 450kB 3.0MB/s 
Collecting eth-hash<1.0.0,>=0.1.0 (from eth_utils)
  Downloading eth_hash-0.1.0-py3-none-any.whl
Collecting toolz>=0.8.0 (from cytoolz<1.0.0,>=0.8.2->eth_utils)
  Downloading toolz-0.9.0.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 10.7MB/s 
Building wheels for collected packages: cytoolz, toolz
  Running setup.py bdist_wheel for cytoolz ... - \ | / - \ | / done
  Stored in directory: /home/circleci/.cache/pip/wheels/b6/66/0c/9a3195246eb242483f1504e492b89f2c570c0ba6307c65373c
  Running setup.py bdist_wheel for toolz ... - \ done
  Stored in directory: /home/circleci/.cache/pip/wheels/57/51/8a/433a9c0a2c65fc1b2a795ae036b932f3339a02e9ae88367659
Successfully built cytoolz toolz
Installing collected packages: chardet, certifi, urllib3, idna, requests, toolz, cytoolz, eth-hash, eth-utils, tqdm
Successfully installed certifi-2018.1.18 chardet-3.0.4 cytoolz-0.9.0 eth-hash-0.1.0 eth-utils-1.0.1 idna-2.6 requests-2.18.4 toolz-0.9.0 tqdm-4.19.6 urllib3-1.22
Traceback (most recent call last):
  File "tests/integration/install_parity.py", line 6, in <module>
    from eth_utils import (
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_utils/__init__.py", line 5, in <module>
    from .abi import (  # noqa: F401
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_utils/abi.py", line 1, in <module>
    from .crypto import keccak
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_utils/crypto.py", line 1, in <module>
    from eth_hash.auto import keccak as keccak_256
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_hash/auto.py", line 8, in <module>
    keccak = Keccak256(auto_choose_backend())
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_hash/utils.py", line 15, in auto_choose_backend
    return choose_available_backend()
  File "/home/circleci/.local/lib/python3.6/site-packages/eth_hash/utils.py", line 52, in choose_available_backend
    SUPPORTED_BACKENDS[0],
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`.
```

### Environment

Run on CircleCI test container.

```sh
Successfully installed certifi-2018.1.18 chardet-3.0.4 cytoolz-0.9.0 eth-hash-0.1.0 eth-utils-1.0.1 idna-2.6 requests-2.18.4 toolz-0.9.0 tqdm-4.19.6 urllib3-1.22
``` 

## How can it be fixed?

Only check for the back end and runtime rather than import time. For big libraries like eth-utils, they may never want to run `keccak`, so warning about the missing backend is a nuisance with little upside.

We can do a lazy load of the backend, and throw up at the first `keccak` call, if necessary.

**Comment by willianpaixao** [comment]
Hey @carver, can we close this issue?
